/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSmartHomeRouteImport } from './routes/app/smart-home'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppRefillRouteImport } from './routes/app/refill'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppFamilyRouteImport } from './routes/app/family'
import { Route as AppEmergencyRouteImport } from './routes/app/emergency'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAiRouteImport } from './routes/app/ai'
import { Route as AppDevicesIndexRouteImport } from './routes/app/devices.index'
import { Route as AppAlertsIndexRouteImport } from './routes/app/alerts.index'
import { Route as AppDevicesIdRouteImport } from './routes/app/devices.$id'
import { Route as AppAlertsIdRouteImport } from './routes/app/alerts.$id'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSmartHomeRoute = AppSmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRefillRoute = AppRefillRouteImport.update({
  id: '/refill',
  path: '/refill',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFamilyRoute = AppFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevicesIndexRoute = AppDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlertsIndexRoute = AppAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevicesIdRoute = AppDevicesIdRouteImport.update({
  id: '/devices/$id',
  path: '/devices/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlertsIdRoute = AppAlertsIdRouteImport.update({
  id: '/alerts/$id',
  path: '/alerts/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/family': typeof AppFamilyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/refill': typeof AppRefillRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/': typeof AppIndexRoute
  '/app/alerts/$id': typeof AppAlertsIdRoute
  '/app/devices/$id': typeof AppDevicesIdRoute
  '/app/alerts/': typeof AppAlertsIndexRoute
  '/app/devices/': typeof AppDevicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/family': typeof AppFamilyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/refill': typeof AppRefillRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app': typeof AppIndexRoute
  '/app/alerts/$id': typeof AppAlertsIdRoute
  '/app/devices/$id': typeof AppDevicesIdRoute
  '/app/alerts': typeof AppAlertsIndexRoute
  '/app/devices': typeof AppDevicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/family': typeof AppFamilyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/refill': typeof AppRefillRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/': typeof AppIndexRoute
  '/app/alerts/$id': typeof AppAlertsIdRoute
  '/app/devices/$id': typeof AppDevicesIdRoute
  '/app/alerts/': typeof AppAlertsIndexRoute
  '/app/devices/': typeof AppDevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ai'
    | '/app/analytics'
    | '/app/emergency'
    | '/app/family'
    | '/app/profile'
    | '/app/refill'
    | '/app/settings'
    | '/app/smart-home'
    | '/app/'
    | '/app/alerts/$id'
    | '/app/devices/$id'
    | '/app/alerts/'
    | '/app/devices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/ai'
    | '/app/analytics'
    | '/app/emergency'
    | '/app/family'
    | '/app/profile'
    | '/app/refill'
    | '/app/settings'
    | '/app/smart-home'
    | '/app'
    | '/app/alerts/$id'
    | '/app/devices/$id'
    | '/app/alerts'
    | '/app/devices'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ai'
    | '/app/analytics'
    | '/app/emergency'
    | '/app/family'
    | '/app/profile'
    | '/app/refill'
    | '/app/settings'
    | '/app/smart-home'
    | '/app/'
    | '/app/alerts/$id'
    | '/app/devices/$id'
    | '/app/alerts/'
    | '/app/devices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/smart-home': {
      id: '/app/smart-home'
      path: '/smart-home'
      fullPath: '/app/smart-home'
      preLoaderRoute: typeof AppSmartHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/refill': {
      id: '/app/refill'
      path: '/refill'
      fullPath: '/app/refill'
      preLoaderRoute: typeof AppRefillRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/family': {
      id: '/app/family'
      path: '/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AppFamilyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/emergency': {
      id: '/app/emergency'
      path: '/emergency'
      fullPath: '/app/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/devices/': {
      id: '/app/devices/'
      path: '/devices'
      fullPath: '/app/devices/'
      preLoaderRoute: typeof AppDevicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/alerts/': {
      id: '/app/alerts/'
      path: '/alerts'
      fullPath: '/app/alerts/'
      preLoaderRoute: typeof AppAlertsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/devices/$id': {
      id: '/app/devices/$id'
      path: '/devices/$id'
      fullPath: '/app/devices/$id'
      preLoaderRoute: typeof AppDevicesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/alerts/$id': {
      id: '/app/alerts/$id'
      path: '/alerts/$id'
      fullPath: '/app/alerts/$id'
      preLoaderRoute: typeof AppAlertsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppFamilyRoute: typeof AppFamilyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRefillRoute: typeof AppRefillRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmartHomeRoute: typeof AppSmartHomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlertsIdRoute: typeof AppAlertsIdRoute
  AppDevicesIdRoute: typeof AppDevicesIdRoute
  AppAlertsIndexRoute: typeof AppAlertsIndexRoute
  AppDevicesIndexRoute: typeof AppDevicesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppFamilyRoute: AppFamilyRoute,
  AppProfileRoute: AppProfileRoute,
  AppRefillRoute: AppRefillRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmartHomeRoute: AppSmartHomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlertsIdRoute: AppAlertsIdRoute,
  AppDevicesIdRoute: AppDevicesIdRoute,
  AppAlertsIndexRoute: AppAlertsIndexRoute,
  AppDevicesIndexRoute: AppDevicesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
